### PR TITLE
Apple IIgs font support (read/write), based on macintosh nfnt support.

### PR DESCRIPTION
**Pull request by ksherlock**
Apple IIgs fonts are more a little-endian NFNT (as of 1985/1986) with an extra header.

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks, that's helpful! I found the documentation you mention and thanks for adding a test as well. Do you happen to know of any original IIgs files around on the internet so I can try them a bit more? I can look around in places like https://www.whatisthe2gs.apple2.org.za/system-applications.html but if you have any tips they're very welcome too :)

**Comment by robhagemans** [comment]
Ah actually I already have a copy of GSOS6.0.4 lying around which includes Courier, Helvetica, Symbol and Times in this format. And you mentioned last year at https://github.com/robhagemans/hoard-of-bitfonts/pull/4 that Shaston 8pt was stored in ROM. Was the 16pt Shaston that you contributed there included in a `.fon` file with the OS as well?

**Comment by robhagemans** [comment]
merged into `develop` branch at 729ff61

**Comment by ksherlock** [comment]
I forgot to mention that Apple's internal documentation is [here](http://www.brutaldeluxe.fr/documentation/cortland/v4_08_AppendixesAtoD.pdf), starting on page 15.

Shaston 16 was included as a font file.  Here's a copy of it as well as the Shaston 8 I extracted from the ROM.

[Shaston.zip](https://github.com/robhagemans/monobit/files/10608822/Shaston.zip)

Here's a copy of all the fonts from the [Golden Orchard](http://digisoft.callapple.org/golden_orchard/)/[Golden Grail](http://digisoft.callapple.org/the_golden_grail/) CD.

[Bitmap.Fonts.zip](https://github.com/robhagemans/monobit/files/10608881/Bitmap.Fonts.zip)

Here's a copy of all the fonts from the [GEnie](https://en.wikipedia.org/wiki/GEnie) online service libraries:

[Genie.zip](https://github.com/robhagemans/monobit/files/10608912/Genie.zip)

**Comment by robhagemans** [comment]
Thanks again, there's a lot of stuff in there!

Another thing, I saw you used my generic copyright notice for the iigs module - was your intention to transfer the copyright? E.g you could also put the contribution under your own name and MIT or similar licence. Either way works for me by the way, just want to make sure I can make the terms explicit.

**Comment by ksherlock** [comment]
That was copied and I didn't put much thought into it...  You can keep the copyright and put my name there for posterity I suppose.

**Comment by robhagemans** [comment]
Sure, I'll update the notice. Thanks!

**Pull request closed without merging**
