### PR TITLE
Apple II MouseGraphics ToolKit Font Format (read only)

### PR DESCRIPTION
**Pull request by ksherlock**
See:
* https://github.com/a2stuff/a2d/tree/main/mgtk/fonts
* https://github.com/a2stuff/a2d/blob/main/mgtk/MGTK.md#font

### CODE REVIEW

**Comment by robhagemans** [comment]
Thanks again, good find!

Question - I think the sample `mp.font` comes from the `a2d` project  you link but I couldn't find a licence there (I may not have looked closely enough yet). 

Sorry to be a bore on this but I'm trying to be careful about licensing in this project, and font files are 'software', so they would need a redistribution licence. This is as opposed to the bitmap font designs themselves by the way, which go under more liberal arrangements in many jurisdictions.

So if the file has no licence or some kind of statement from the copyright holder that they're happy for it to be distributed I'd rather leave it out here. I've been thinking I might add a wget script for test files with unclear redistribution terms - which are in fact freely available but have no clear terms so can't be included in the code base.

By the way, I'd like to keep the code style in the repo more or less consistent - things like no blank lines inside functions except around nested functions. Basically this style: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html . It's fine for now as I can make it consistent later, but maybe something to consider if you have more ideas in the pipeline :)

**Comment by ksherlock** [comment]
The mp.font was originally from Mouse Paint.  I've replaced it with a new front based on 4x6.

**Comment by robhagemans** [comment]
Thanks!

**Comment by robhagemans** [comment]
Merged into `develop` branch at  244ec2d

**Pull request closed without merging**
